# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pilotcodepush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pilotcodepush
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'
  

  target 'pilotcodepushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pilotcodepush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pilotcodepush-tvOS

  target 'pilotcodepush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
